"""Canonical Python implementation of the Karma score -> collateral ratio curve.

This module and contracts/src/RiskParams.sol are two spellings of one function.
They are kept honest by contracts/test/RiskParamsParity.t.sol, which reads the
fixture emitted here and asserts equality for every score in [300, 900].

Integer arithmetic only. Python's // and Solidity's / agree exactly on
non-negative integers, so "agree" means equal, not close.

    python3 model/risk_curve.py --dump contracts/test/fixtures/ratio_curve.json
    python3 model/risk_curve.py --show 720
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MIN_SCORE = 300
MAX_SCORE = 900
SCORE_SPAN = MAX_SCORE - MIN_SCORE  # 600

# Defaults must match the initialisers in RiskParams.sol.
RATIO_AT_MIN_SCORE = 15_000  # 150% collateral at the bottom of the range
RATIO_AT_MAX_SCORE = 11_000  # 110% collateral at the top of the range
LIQUIDATION_BUFFER_BPS = 500
ABS_MIN_RATIO_BPS = 10_500
ABS_MAX_RATIO_BPS = 30_000
BPS = 10_000


class ScoreOutOfRange(ValueError):
    pass


def ratio_bps(
    score: int,
    ratio_at_min: int = RATIO_AT_MIN_SCORE,
    ratio_at_max: int = RATIO_AT_MAX_SCORE,
) -> int:
    """Collateral ratio in basis points required to borrow at `score`."""
    if not isinstance(score, int) or isinstance(score, bool):
        raise TypeError("score must be an int")
    if score < MIN_SCORE or score > MAX_SCORE:
        raise ScoreOutOfRange(f"score {score} outside [{MIN_SCORE}, {MAX_SCORE}]")
    drop = ratio_at_min - ratio_at_max
    return ratio_at_min - ((score - MIN_SCORE) * drop) // SCORE_SPAN


def liquidation_ratio_bps(
    score: int,
    ratio_at_min: int = RATIO_AT_MIN_SCORE,
    ratio_at_max: int = RATIO_AT_MAX_SCORE,
    buffer_bps: int = LIQUIDATION_BUFFER_BPS,
) -> int:
    """Ratio at which a position at `score` becomes liquidatable."""
    liq = ratio_bps(score, ratio_at_min, ratio_at_max) - buffer_bps
    return max(liq, ABS_MIN_RATIO_BPS)


def collateral_required(borrow_amount_usd: float, score: int) -> float:
    """Collateral in USD needed to borrow `borrow_amount_usd` at `score`."""
    return borrow_amount_usd * ratio_bps(score) / BPS


def capital_efficiency_lift(score: int, baseline_bps: int = RATIO_AT_MIN_SCORE) -> float:
    """Fraction of collateral freed versus a flat `baseline_bps` protocol."""
    return 1.0 - ratio_bps(score) / baseline_bps


def curve() -> list[dict[str, int]]:
    return [
        {
            "score": s,
            "ratioBps": ratio_bps(s),
            "liquidationRatioBps": liquidation_ratio_bps(s),
        }
        for s in range(MIN_SCORE, MAX_SCORE + 1)
    ]


def fixture() -> dict:
    rows = curve()
    return {
        "_comment": (
            "Generated by model/risk_curve.py. Do not edit by hand. "
            "Regenerate with: make parity-fixture"
        ),
        "minScore": MIN_SCORE,
        "maxScore": MAX_SCORE,
        "ratioAtMinScore": RATIO_AT_MIN_SCORE,
        "ratioAtMaxScore": RATIO_AT_MAX_SCORE,
        "liquidationBufferBps": LIQUIDATION_BUFFER_BPS,
        "absMinRatioBps": ABS_MIN_RATIO_BPS,
        "absMaxRatioBps": ABS_MAX_RATIO_BPS,
        "ratios": [r["ratioBps"] for r in rows],
        "liquidationRatios": [r["liquidationRatioBps"] for r in rows],
    }


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dump", metavar="PATH", help="write the parity fixture to PATH")
    p.add_argument("--show", metavar="SCORE", type=int, help="print the ratio for one score")
    args = p.parse_args(argv)

    if args.show is not None:
        s = args.show
        print(
            f"score={s} ratio={ratio_bps(s)}bps "
            f"liquidation={liquidation_ratio_bps(s)}bps "
            f"lift={capital_efficiency_lift(s):.1%}"
        )
        return 0

    if args.dump:
        out = Path(args.dump)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(fixture(), indent=2) + "\n")
        print(f"wrote {out} ({MAX_SCORE - MIN_SCORE + 1} scores)")
        return 0

    for row in curve()[::50]:
        print(f"{row['score']:>4}  {row['ratioBps']:>6}  {row['liquidationRatioBps']:>6}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
