// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {KarmaFixture} from "./utils/KarmaFixture.sol";

/// @notice Proves RiskParams.sol and model/risk_curve.py compute the same function.
///
/// @dev The fixture is generated by the Python module, not written by hand:
///
///        python3 model/risk_curve.py --dump contracts/test/fixtures/ratio_curve.json
///
///      `make test` regenerates it before running, so a change to either side that is
///      not mirrored in the other fails here rather than silently mispricing loans.
contract RiskParamsParityTest is KarmaFixture {
    string internal constant FIXTURE = "./test/fixtures/ratio_curve.json";

    function test_constantsAgree() public view {
        string memory json = vm.readFile(FIXTURE);

        assertEq(vm.parseJsonUint(json, ".minScore"), riskParams.MIN_SCORE(), "MIN_SCORE");
        assertEq(vm.parseJsonUint(json, ".maxScore"), riskParams.MAX_SCORE(), "MAX_SCORE");
        assertEq(vm.parseJsonUint(json, ".ratioAtMinScore"), riskParams.ratioAtMinScore(), "curve top");
        assertEq(vm.parseJsonUint(json, ".ratioAtMaxScore"), riskParams.ratioAtMaxScore(), "curve bottom");
        assertEq(
            vm.parseJsonUint(json, ".liquidationBufferBps"), riskParams.liquidationBufferBps(), "liquidation buffer"
        );
        assertEq(vm.parseJsonUint(json, ".absMinRatioBps"), riskParams.ABS_MIN_RATIO_BPS(), "hard floor");
        assertEq(vm.parseJsonUint(json, ".absMaxRatioBps"), riskParams.ABS_MAX_RATIO_BPS(), "hard ceiling");
    }

    function test_collateralRatioAgreesAcrossFullScoreRange() public view {
        string memory json = vm.readFile(FIXTURE);
        uint256[] memory pythonRatios = vm.parseJsonUintArray(json, ".ratios");

        uint16 minScore = riskParams.MIN_SCORE();
        uint16 maxScore = riskParams.MAX_SCORE();
        assertEq(pythonRatios.length, uint256(maxScore - minScore + 1), "fixture length");

        for (uint16 s = minScore; s <= maxScore; s++) {
            assertEq(
                riskParams.collateralRatioBps(s),
                pythonRatios[s - minScore],
                string.concat("solidity and python disagree at score ", vm.toString(s))
            );
        }
    }

    function test_liquidationRatioAgreesAcrossFullScoreRange() public view {
        string memory json = vm.readFile(FIXTURE);
        uint256[] memory pythonLiq = vm.parseJsonUintArray(json, ".liquidationRatios");

        uint16 minScore = riskParams.MIN_SCORE();
        uint16 maxScore = riskParams.MAX_SCORE();

        for (uint16 s = minScore; s <= maxScore; s++) {
            assertEq(
                riskParams.liquidationRatioBps(s),
                pythonLiq[s - minScore],
                string.concat("liquidation ratio disagrees at score ", vm.toString(s))
            );
        }
    }
}
