"""Generate a cross-language signature fixture.

Python signs an attestation here; contracts/test/CrossLanguageSignature.t.sol
verifies that exact signature against the real ScoreOracle. If eth-account's
EIP-712 and our Solidity ever drift apart, that test fails - which is the only
way to find out before a judge does.

The trick is the verifying contract address: EIP-712 binds it, so Python has to
know where the oracle will live before Solidity deploys it. Both sides agree on
a fixed deployer at nonce 0 and compute the same CREATE address.

    python -m signer.fixtures

The signing key below is anvil's well-known development account #1. It is
public, it secures nothing, and it is checked in on purpose so the fixture is
reproducible by anyone.
"""

from __future__ import annotations

import json
from pathlib import Path

from eth_account import Account
from eth_utils import keccak, to_checksum_address

from . import attestation as att_mod

OUT = Path("contracts/test/fixtures/python_attestation.json")

# anvil development account #1 - public, not a secret.
SIGNER_PRIVATE_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

DEPLOYER = "0x00000000000000000000000000000000000C0DE1"
CHAIN_ID = 31337
WALLET = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
SCORE = 742
MODEL_VERSION = 1
FEATURE_HASH = "0x" + keccak(text="karma-cross-language-fixture").hex()
ISSUED_AT = 1_787_000_000
TTL = 3_600
NONCE = 424_242


def create_address(deployer: str, nonce: int) -> str:
    """The address CREATE gives a contract deployed by `deployer` at `nonce`.

    Only nonce 0 is needed here, which RLP-encodes as the single byte 0x80.
    """
    if nonce != 0:
        raise ValueError("only nonce 0 is supported; that is all the fixture needs")
    payload = b"\xd6\x94" + bytes.fromhex(deployer.removeprefix("0x")) + b"\x80"
    return to_checksum_address(keccak(payload)[12:])


def build_fixture() -> dict:
    oracle = create_address(DEPLOYER, 0)
    att = att_mod.build(
        wallet=WALLET,
        score=SCORE,
        model_version=MODEL_VERSION,
        feature_hash=FEATURE_HASH,
        ttl_seconds=TTL,
        now=ISSUED_AT,
        nonce=NONCE,
    )
    signed = att_mod.sign(att, CHAIN_ID, oracle, SIGNER_PRIVATE_KEY)

    return {
        "_comment": (
            "Generated by `python -m signer.fixtures`. Signed by eth-account, verified "
            "by CrossLanguageSignature.t.sol against the real ScoreOracle."
        ),
        "chainId": CHAIN_ID,
        "deployer": to_checksum_address(DEPLOYER),
        "deployerNonce": 0,
        "scoreOracle": oracle,
        "signer": signed["signer"],
        "issuedAt": ISSUED_AT,
        "wallet": att.wallet,
        "score": att.score,
        "modelVersion": att.modelVersion,
        "featureHash": att.featureHash,
        "expiry": att.expiry,
        "nonce": att.nonce,
        "signature": signed["signature"],
        "digest": signed["digest"],
        "domainSeparator": signed["domain_separator"],
        "structHash": signed["struct_hash"],
        "calldata": att_mod.calldata(att, signed["signature"]),
    }


def main() -> int:
    fixture = build_fixture()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {OUT}")
    print(f"  oracle    {fixture['scoreOracle']}  (CREATE from {fixture['deployer']} nonce 0)")
    print(f"  signer    {fixture['signer']}")
    print(f"  digest    {fixture['digest']}")
    assert Account.from_key(SIGNER_PRIVATE_KEY).address == fixture["signer"]
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
